# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2024 noah
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Check existence of Calibre-Web systemd service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ calibre_web_identifier }}.service"
  register: calibre_web_service_stat

- name: Uninstall Calibre-Web systemd services and files
  when: calibre_web_service_stat.stat.exists | bool
  block:
    - name: Ensure Calibre-Web systemd service is stopped
      ansible.builtin.service:
        name: "{{ calibre_web_identifier }}"
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure Calibre-Web systemd service does not exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ calibre_web_identifier }}.service"
        state: absent

    - name: Ensure Calibre-Web support files do not exist
      ansible.builtin.file:
        path: "{{ calibre_web_base_path }}/{{ item }}"
        state: absent
      with_items:
        - env
        - labels

    - name: Ensure Calibre-Web image source files path does not exist
      ansible.builtin.file:
        path: "{{ calibre_web_container_image_self_build_src_files_path }}"
        state: absent

    - name: Ensure Calibre-Web container network does not exist
      when: calibre_web_container_network_deletion_enabled
      block:
        - name: Ensure Calibre-Web container network does not exist via community.docker.docker_network
          when: devture_systemd_docker_base_container_network_creation_method == 'ansible-module'
          community.docker.docker_network:
            name: "{{ calibre_web_container_network }}"
            state: absent
          register: calibre_web_network_deletion_result

        - name: Ensure Calibre-Web container network does not exist via ansible.builtin.command
          when: devture_systemd_docker_base_container_network_creation_method == 'command'
          ansible.builtin.command:
            cmd: >-
              {{ devture_systemd_docker_base_host_command_docker }} network rm
              {{ calibre_web_container_network }}
          register: calibre_web_network_deletion_result
          changed_when: calibre_web_container_network in calibre_web_network_deletion_result.stdout

- name: Check existence of Calibre-Web internal database and config path
  ansible.builtin.stat:
    path: "{{ calibre_web_config_path }}"
  register: calibre_web_config_path_stat

# We just want to notify the user. Deleting data is too destructive.
- name: Notify if Calibre-Web internal database and config path remains
  when: calibre_web_config_path_stat.stat.exists | bool
  ansible.builtin.set_fact:
    devture_playbook_runtime_messages_list: |
      {{
        devture_playbook_runtime_messages_list | default([])
        +
        [
          "Note: As the local Calibre-Web instance has been removed, internal database and config data remain in `" + calibre_web_config_path + "`. Feel free to delete it."
        ]
      }}

- name: Check existence of Calibre-Web preexisting calibre database path
  ansible.builtin.stat:
    path: "{{ calibre_web_books_path }}"
  register: calibre_web_books_path_stat

# We just want to notify the user. Deleting data is too destructive.
- name: Notify if Calibre-Web preexisting calibre database path remains
  when: calibre_web_books_path_stat.stat.exists | bool
  ansible.builtin.set_fact:
    devture_playbook_runtime_messages_list: |
      {{
        devture_playbook_runtime_messages_list | default([])
        +
        [
          "Note: As the local Calibre-Web instance has been removed, preexisting calibre database remains in `" + calibre_web_books_path + "`. Feel free to delete it."
        ]
      }}
